=== microrat/epam-lab-2022/lab3/src/XMLresources/beer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:tns="https://www.example.org/beer"
	xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://www.example.org/beer"
	elementFormDefault="qualified">

	<element name="BeerList" type="tns:BeerList" />

	<complexType name="BeerList">
		<sequence>
			<element name="Beer" maxOccurs="unbounded" type="tns:Beer" />
		</sequence>
		<attribute name="id" type="ID" use="required" />
	</complexType>

	<complexType name="Beer">
		<sequence>
			<element name="Title" type="string" />
			<element name="BeerType" type="tns:BeerType" />
			<element name="Al" type="boolean" />
			<element name="Manufacturer" type="string" />
			<element name="Chars" type="tns:Chars" />
			<element name="Ingridients" type="tns:Ingridients" />
		</sequence>
	</complexType>

	<simpleType name="BeerType">
		<restriction base="string">
			<enumeration value="Lager" />
			<enumeration value="Light" />
			<enumeration value="Dark" />
			<enumeration value="Porter" />
		</restriction>
	</simpleType>

	<complexType name="Chars">
		<sequence>
			<element name="Filtered" type="boolean" />
			<element name="Calories" type="float"></element>
			<element name="TypeOfFilling" type="tns:TypeOfFilling"></element>
			<element name="NumberOfTurns" type="tns:NumberOfTurns"></element>
			<element name="Tranparency" type="tns:Tranparency"></element>
		</sequence>
	</complexType>

	<complexType name="TypeOfFilling">
		<sequence>
			<element name="Volume" type="tns:Volume" />
			<element name="MaterialType" type="tns:MaterialType" />
		</sequence>
	</complexType>

	<simpleType name="MaterialType">
		<restriction base="string">
			<enumeration value="Plastic" />
			<enumeration value="Glass" />
			<enumeration value="Steel" />
			<enumeration value="Porter" />
		</restriction>
	</simpleType>

	<simpleType name="Volume">
		<restriction base="float">
			<minExclusive value="0"></minExclusive>
		</restriction>
	</simpleType>

	<simpleType name="NumberOfTurns">
		<restriction base="float">
			<minInclusive value="0"></minInclusive>
		</restriction>
	</simpleType>

	<simpleType name="Tranparency">
		<restriction base="string">
			<pattern value="[1-9][0-9]?[%]"></pattern>
		</restriction>
	</simpleType>

	<complexType name="Ingridients">
		<sequence>
			<element name="Ingridient" type="tns:Ingridient"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="Ingridient">
		<sequence>
			<element name="Name" type="tns:IngrideintName" />
			<element name="Amount" type="float" />
		</sequence>
	</complexType>

	<simpleType name="IngrideintName">
		<restriction base="string">
			<enumeration value="Water" />
			<enumeration value="Malt" />
			<enumeration value="Hop" />
			<enumeration value="Sugar" />
		</restriction>
	</simpleType>

</schema>

=== microrat/epam-lab-2022/lab3/src/XMLresources/beer-writer.xml
<?xml version="1.0" encoding="UTF-8"?><tns:BeerList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="https://www.example.org/BeerList" xsi:schemaLocation="http://www.example.org/BeerList beer.xsd "><tns:Beer id="id1"><tns:Title>Baltika 7</tns:Title><tns:BeerType>Light</tns:BeerType><tns:Al>true</tns:Al><tns:Manufacturer>Baltika</tns:Manufacturer><tns:Chars><tns:Filtered>true</tns:Filtered><tns:Calories>216.0</tns:Calories><tns:TypeOfFilling><tns:MaterialType>Steel</tns:MaterialType><tns:Volume>0.33</tns:Volume></tns:TypeOfFilling><tns:NumberOfTurns>12.0</tns:NumberOfTurns><tns:Tranparency>16%</tns:Tranparency></tns:Chars><tns:Ingridients><tns:Ingridient><tns:IngrideintName>Water</tns:IngrideintName><tns:Amount>130.0</tns:Amount></tns:Ingridient><tns:Ingridient><tns:IngrideintName>Sugar</tns:IngrideintName><tns:Amount>13.0</tns:Amount></tns:Ingridient><tns:Ingridient><tns:IngrideintName>Malt</tns:IngrideintName><tns:Amount>54.0</tns:Amount></tns:Ingridient></tns:Ingridients></tns:Beer><tns:Beer id="id2"><tns:Title>Белый медведь</tns:Title><tns:BeerType>Porter</tns:BeerType><tns:Al>true</tns:Al><tns:Manufacturer>Россия</tns:Manufacturer><tns:Chars><tns:Filtered>true</tns:Filtered><tns:Calories>333.0</tns:Calories><tns:TypeOfFilling><tns:MaterialType>Plastic</tns:MaterialType><tns:Volume>1.5</tns:Volume></tns:TypeOfFilling><tns:NumberOfTurns>5.0</tns:NumberOfTurns><tns:Tranparency>40%</tns:Tranparency></tns:Chars><tns:Ingridients><tns:Ingridient><tns:IngrideintName>Water</tns:IngrideintName><tns:Amount>130.0</tns:Amount></tns:Ingridient><tns:Ingridient><tns:IngrideintName>Sugar</tns:IngrideintName><tns:Amount>13.0</tns:Amount></tns:Ingridient><tns:Ingridient><tns:IngrideintName>Malt</tns:IngrideintName><tns:Amount>54.0</tns:Amount></tns:Ingridient></tns:Ingridients></tns:Beer><tns:Beer id="id3"><tns:Title>Охота крепкое</tns:Title><tns:BeerType>Lager</tns:BeerType><tns:Al>true</tns:Al><tns:Manufacturer>Россия</tns:Manufacturer><tns:Chars><tns:Filtered>false</tns:Filtered><tns:Calories>200.0</tns:Calories><tns:TypeOfFilling><tns:MaterialType>Plastic</tns:MaterialType><tns:Volume>2.5</tns:Volume></tns:TypeOfFilling><tns:NumberOfTurns>5.0</tns:NumberOfTurns><tns:Tranparency>16%</tns:Tranparency></tns:Chars><tns:Ingridients><tns:Ingridient><tns:IngrideintName>Water</tns:IngrideintName><tns:Amount>110.0</tns:Amount></tns:Ingridient><tns:Ingridient><tns:IngrideintName>Sugar</tns:IngrideintName><tns:Amount>13.0</tns:Amount></tns:Ingridient></tns:Ingridients></tns:Beer></tns:BeerList>

=== microrat/epam-lab-2022/lab3/src/XMLresources/beer.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:BeerList xmlns:tns="https://www.example.org/BeerList"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://www.example.org/BeerList beer.xsd ">
	<tns:Beer id="id3">
		<tns:Title>Охота крепкое</tns:Title>
		<tns:BeerType>Lager</tns:BeerType>
		<tns:Al>true</tns:Al>
		<tns:Manufacturer>Россия</tns:Manufacturer>
		<tns:Chars>
			<tns:Filtered>false</tns:Filtered>
			<tns:Calories>200</tns:Calories>
			<tns:TypeOfFilling>
				<tns:Volume>2.5</tns:Volume>
				<tns:MaterialType>Plastic</tns:MaterialType>
			</tns:TypeOfFilling>
			<tns:NumberOfTurns>5</tns:NumberOfTurns>
			<tns:Tranparency>16%</tns:Tranparency>
		</tns:Chars>
		<tns:Ingridients>
			<tns:Ingridient>
				<tns:IngrideintName>Water</tns:IngrideintName>
				<tns:Amount>110</tns:Amount>
			</tns:Ingridient>
			<tns:Ingridient>
				<tns:IngrideintName>Sugar</tns:IngrideintName>
				<tns:Amount>13</tns:Amount>
			</tns:Ingridient>
		</tns:Ingridients>
	</tns:Beer>
	<tns:Beer id="id1">
		<tns:Title>Baltika 7</tns:Title>
		<tns:BeerType>Light</tns:BeerType>
		<tns:Al>true</tns:Al>
		<tns:Manufacturer>Baltika</tns:Manufacturer>
		<tns:Chars>
			<tns:Filtered>true</tns:Filtered>
			<tns:Calories>216</tns:Calories>
			<tns:TypeOfFilling>
				<tns:Volume>0.33</tns:Volume>
				<tns:MaterialType>Steel</tns:MaterialType>
			</tns:TypeOfFilling>
			<tns:NumberOfTurns>12</tns:NumberOfTurns>
			<tns:Tranparency>16%</tns:Tranparency>
		</tns:Chars>
		<tns:Ingridients>
			<tns:Ingridient>
				<tns:IngrideintName>Water</tns:IngrideintName>
				<tns:Amount>130</tns:Amount>
			</tns:Ingridient>
			<tns:Ingridient>
				<tns:IngrideintName>Sugar</tns:IngrideintName>
				<tns:Amount>13</tns:Amount>
			</tns:Ingridient>
			<tns:Ingridient>
				<tns:IngrideintName>Malt</tns:IngrideintName>
				<tns:Amount>54</tns:Amount>
			</tns:Ingridient>
		</tns:Ingridients>
	</tns:Beer>
	<tns:Beer id="id2">
		<tns:Title>Белый медведь</tns:Title>
		<tns:BeerType>Porter</tns:BeerType>
		<tns:Al>true</tns:Al>
		<tns:Manufacturer>Россия</tns:Manufacturer>
		<tns:Chars>
			<tns:Filtered>true</tns:Filtered>
			<tns:Calories>333</tns:Calories>
			<tns:TypeOfFilling>
				<tns:Volume>1.5</tns:Volume>
				<tns:MaterialType>Plastic</tns:MaterialType>
			</tns:TypeOfFilling>
			<tns:NumberOfTurns>5</tns:NumberOfTurns>
			<tns:Tranparency>40%</tns:Tranparency>
		</tns:Chars>
		<tns:Ingridients>
			<tns:Ingridient>
				<tns:IngrideintName>Water</tns:IngrideintName>
				<tns:Amount>130</tns:Amount>
			</tns:Ingridient>
			<tns:Ingridient>
				<tns:IngrideintName>Sugar</tns:IngrideintName>
				<tns:Amount>13</tns:Amount>
			</tns:Ingridient>
			<tns:Ingridient>
				<tns:IngrideintName>Malt</tns:IngrideintName>
				<tns:Amount>54</tns:Amount>
			</tns:Ingridient>
		</tns:Ingridients>
	</tns:Beer>
	


</tns:BeerList>
